### ISSUE TITLE
Updates on ROS Melodic

### ISSUE THREAD

**Issue by nihar0602** [MyungHaSong/DenseFusion_ROS#10]
Hi @MyoungHaSong, 
Thanks for your work. 

I appreciate it. 
I want to know how to make it run on ROS Melodic since ROS Kinetic is out of service now.
Do you have any approach to do that? 

Looking forward to your reply. 

Thanks!

**Comment by MyoungHaSong** [comment]
Sorry, but I haven't tried it.
