### ISSUE TITLE
utils.py

### ISSUE THREAD

**Issue by WinglokWong616** [MyungHaSong/DenseFusion_ROS#11]
Hi! Nice work! I am currently trying your code with Python3.6. However, when running
`from utils import reverse_one_hot, compute_global_accuracy, fast_hist, per_class_iu, cal_miou` 
I got the error below:
`ImportError: bad magic number in 'utils': b'\x03\xf3\r\n'`.
It appears to be a problem about different python version used. I wonder if it is possible for you to provide utils.py instead of utils.pyc?
My team will appreciate it if you do. It will be of much help to us.

**Comment by Lin1225** [comment]
Hi, @WinglokWong616 
I think this [utils.py](https://github.com/ooooverflow/BiSeNet/blob/284a8f6782c0418d1dbd12269432cb4f0eb92426/utils.py) file can work.

**Comment by WinglokWong616** [comment]
Thanks a lot. I managed to implement the code with Python2.7 using utils.pyc, this issue should probably be closed 

> Hi, @WinglokWong616 I think this [utils.py](https://github.com/ooooverflow/BiSeNet/blob/284a8f6782c0418d1dbd12269432cb4f0eb92426/utils.py) file can work.
